image: node:16.3.0

stages:
  - deploy

variables:
  SELFHOST: "auth"

deploy:
  image: docker/compose:latest
  stage: deploy
  tags:
    - front-docker-1
  before_script:
    - if [[ "$CI_COMMIT_REF_NAME" == "master" ]] || [[ "$CI_COMMIT_REF_NAME" == "main" ]]; then export SELF_DOMAIN_NAME='' ; else export SELF_DOMAIN_NAME=-$CI_COMMIT_REF_NAME;  fi;
    - sed 's/servername/'"$CI_COMMIT_REF_NAME"'/g' docker-compose.yaml >docker-compose-updated.yaml
    - if [[ "$CI_COMMIT_REF_NAME" == "master" ]] || [[ "$CI_COMMIT_REF_NAME" == "main" ]]; then sed -i  's/LC-RUNCOMMAND/["pnpm", "run", "prd"]/g' Dockerfile; else sed -i  's/LC-RUNCOMMAND/["pnpm", "run", "beta"]/g' Dockerfile;  fi;
    - cat docker-compose-updated.yaml
  script:
    - docker-compose -f docker-compose-updated.yaml up -d --build
    - echo ${SELFHOST}${SELF_DOMAIN_NAME}.abclive.cloud
