image: node:16.3.0

stages:
  - deploy
  - notification

variables:
  APP: "auth"

deploy:
  image: docker/compose:latest
  stage: deploy
  tags:
    - front-docker-1
  before_script:
    - if [[ "$CI_COMMIT_REF_NAME" == "master" ]] || [[ "$CI_COMMIT_REF_NAME" == "main" ]]; then  export GIT_BRANCH=''; 
      export CICD_HOOK_URL="https://open.feishu.cn/open-apis/bot/v2/hook/180e3142-5b21-4442-ae35-f9dc96ee29c5";
      sed -i  's/LC-RUNCOMMAND/["pnpm", "run", "prd"]/g' Dockerfile; 
      else 
      export GIT_BRANCH=-$CI_COMMIT_REF_NAME ; 
      export CICD_HOOK_URL="https://open.feishu.cn/open-apis/bot/v2/hook/f0b1358b-38ce-4f01-b629-64c0d2fbe854";
      sed -i  's/LC-RUNCOMMAND/["pnpm", "run", "beta"]/g' Dockerfile; fi;
  script:
    - docker-compose  up -d --build
    - echo $GIT_BRANCH
    - cat Dockerfile
    - cat docker-compose.yaml
    - echo https://${APP}${GIT_BRANCH}.abclive.cloud  

notification:
  stage: notification
  tags:
    - shell-1
  script:
    - source ./depoly/notification.sh